### ISSUE TITLE
Error during scan but reports no errors

### ISSUE THREAD

**Issue by johansmitsnl** [restic/restic#2544]
Output of `restic version` restic 0.9.5 compiled with go1.12.4 on linux/amd64
--------------------------

How did you run restic exactly? 
-------------------------------

* `/bin/restic_0.9.5 backup /var/lib/postgresql/data --quiet --json --host host-0 --cache-dir /tmp/restic-cache --cleanup-cache`

```
{"message_type":"error","error":{},"during":"archival","item":"/var/lib/postgresql/data"}
{"message_type":"error","error":{},"during":"scan","item":"/var/lib/postgresql/data"}
I0112 12:47:26.148290       1 commands.go:348] sh-output: {"message_type":"status","percent_done":0,"error_count":1}
{"message_type":"summary","files_new":0,"files_changed":0,"files_unmodified":0,"dirs_new":3,"dirs_changed":0,"dirs_unmodified":0,"data_blobs":0,"tree_blobs":4,"data_added":1050,"total_files_processed":0,"total_bytes_processed":0,"total_duration":0.453157947,"snapshot_id":"36d1dfcc"}
{"message_type":"summary","files_new":0,"files_changed":0,"files_unmodified":0,"dirs_new":3,"dirs_changed":0,"dirs_unmodified":0,"data_blobs":0,"tree_blobs":4,"data_added":1050,"total_files_processed":0,"total_bytes_processed":0,"total_duration":0.453157947,"snapshot_id":"36d1dfcc"}
{"message_type":"status","percent_done":0,"error_count":1}

I0112 12:47:26.148520       1 commands.go:252] Checking integrity of repository
[golang-sh]$ /bin/restic_0.9.5 check --cache-dir /tmp/restic-cache
I0112 12:47:27.275740       1 commands.go:348] sh-output: using temporary cache in /tmp/restic-cache/restic-check-cache-435494749
created new cache in /tmp/restic-cache/restic-check-cache-435494749
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

AWS S3

Expected behavior
-----------------

Backup the data

Actual behavior
---------------

Skipped data

Steps to reproduce the behavior
-------------------------------

* Install stash
* Make a repository and backup configuration
* Trigger the backup configuraration

```yaml
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: deployment.postgres
  namespace: infrastructure
spec:
  backend:
    s3:
      endpoint: 's3.eu-central-1.amazonaws.com'
      bucket: 'kubernetes'
      prefix: 'kubernetes/infrastructure/postgres'
    storageSecretName: s3-secret

---

apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: deployment.postgres
  namespace: infrastructure
spec:
  repository:
    name: deployment.postgres
  schedule: '0 0 * * *'
  target:
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: postgres
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      subPath: data
      name: data-volume
    paths:
    - /var/lib/postgresql/data
  retentionPolicy:
    name: 'keep-last-31'
    keepLast: 31
    prune: true
```

Unknown why it can't scan/archive the directory and why it does not report a clear error.

Do you have any idea what may have caused this? There are some 
-----------------------------------------------

No

Do you have an idea how to solve the issue?
-------------------------------------------

No

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes for many years it is my goto backup system!
