### ISSUE TITLE
x509 error when init aws s3 repo from restic arm pods

### ISSUE THREAD

**Issue by mickkael** [restic/restic#2746]
Output of `restic version`
--------------------------
ARM
```
# restic version
restic 0.9.6 compiled with go1.13.4 on linux/arm64
```
AMD
```
# restic version 
restic 0.9.6 compiled with go1.13.4 on linux/amd64
```

How did you run restic exactly?
-------------------------------
Pods deployed by velero v1.3.1, deployed by the helm chart velero-2.9.15
init container velero-plugin-for-aws:v1.0.1
the cluster is a mixed of arm64 (rpi 3 and 4) and amd64 nodes.
arm64 are running Ubuntu 20.04. amd64 are running Ubuntu 18.04.4
Velero pod runs on amd64
Cluster is k3s based, v1.17.4+k3s1
Velero backup runs correctly and succesful for everything but volumes. volumes from pods hosted on amd64 nodes are backup succesfully. On arm64 nodes, volume backup is failing, but kubernetes objects backup is successful.

helm values:
```
---
backupsEnabled: false
snapshotsEnabled: false
configuration:
  provider: aws
  backupStorageLocation:
    name: aws
    provider: aws
    bucket: <myBucket>
    config:
      region: ":<AWSregion>"
use-volume-snapshots: false
cleanUpCRDs: false
initContainers:
  - name: velero-plugin-for-aws
    image: "velero/velero-plugin-for-aws:v1.0.1"
    volumeMounts:
      - mountPath: /target
        name: plugins
    env:
      - name: TZ
        value: Asia/Singapore
nodeSelector:
  kubernetes.io/arch: amd64
credentials:
  existingSecret: s3-velero-creds
deployRestic: true
installCRDs: false
```
```
---
#default_backupstoragelocation.yaml
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: <myBucket>
  config:
    region: <AWSregion>
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
S3 AWS

Expected behavior
-----------------
Init should complete without any certificate error on amazonaws.com, as it does with an amd64 arch

Actual behavior
---------------
ARM64
```
# restic -r s3:s3-<AWSregion>.amazonaws.com/<myBucket>/restic/<myNS> init
Fatal: create repository at s3:s3-<AWSregion>.amazonaws.com/<myBucket>/restic/<myNS> failed: client.BucketExists: Head https://<myBucket>.s3.dualstack.<AWSregion>.amazonaws.com/: x509: certificate signed by unknown authority
```

AMD64
```
# restic -r s3:s3-<AWSregion>.amazonaws.com/<myBucket>/restic/<myNS> init
enter password for new repository: 
```

Steps to reproduce the behavior
-------------------------------
the information above are sufficient to reproduce

Do you have any idea what may have caused this?
-----------------------------------------------
Not for now. I'll add in the issue if my troubleshooting progress

Do you have an idea how to solve the issue?
-------------------------------------------
Not for now. I'll add in the issue if my troubleshooting progress

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
not today but I hope tomorrow :)
