### ISSUE TITLE
Unexpected behavior after removing cache and cache size keeps growing

### ISSUE THREAD

**Issue by Jannick94** [restic/restic#3552]
Quick summary:
--------------------------
I run scheduled Restic commands within a cron docker container. I use a volume for the restic cache to persist this data between container reboots. I backup to 2 backends: AWS S3 and DigitalOcean Spaces. The repositories are ~250GB in size each.
First issue: when I remove the local cache and run a backup it's just a quick as with the cache being available.  
Second issue: the cache size keeps growing over time even while I run hourly `forget` commands with the `--cleanup-cache` flag.

**Please say if you need more information on certain steps or whatever, I'm happy to provide them.**

Output of `restic version`
--------------------------
`restic 0.9.6 compiled with go1.13.10 on linux/amd64`

How did you run restic exactly?
-------------------------------
We schedule different Restic commands using a docker container running cronjobs. We run a `backup` every 30 minutes at xx:18 and xx:48. We run a `forget` command hourly at xx:35 and we prune the repositories weekly.

Within our `docker-compose.yml` file we have a volume for the cache data mounted to this container:

```
cron:
        build:
            context: ./cron
            dockerfile: Dockerfile
        container_name: ${COMPOSE_PROJECT_NAME}-cron
        restart: unless-stopped
        working_dir: /var/log/cron
        environment:
            - RESTIC_PASSWORD=${RESTIC_PASSWORD}
        volumes:
            - ../:/var/www
            - restic-cache:/home/${HOST_USERNAME}/.cache/restic // this is the volume mount
        networks:
            - application-network

...

volumes:
    restic-cache:
        driver: local
```

When running `restic cache` from within this container we get the following output:
```
Repo ID     Last Used   Old  Size
----------------------------------------
bb256f1dc6  0 days ago        49.613 GiB
7ae1c44bde  0 days ago        50.102 GiB
----------------------------------------
2 cache dirs in /home/deployer/.cache/restic
```

So that seems to be working fine. When I delete the cache with: `restic cache --cleanup --max-age=0` (any other age like 1, 2 etc won't work, Restic returns that it can't find old cache directories) and run a backup afterwards I would have expected Restic to be slower because of the cache missing, this however doesn't seem to be the case, the backup process is just as quick as it was before removing the cache (about 1,5/2minutes per repository for about 250GB of files)

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
We backup to AWS S3 and DigitalOcean Spaces.

Expected behavior
-----------------
I expect Restic to be slow(er) after removing the local cache. Also I'm not sure I understand why the cache directories keep on getting bigger over time when we run (as stated above) hourly `forget` commands with the `--cleanup-cache` flag. 

Actual behavior
---------------
The backup process is just as quick as it is with the cache present. The cache directory size keeps getting bigger, I would expect the cache directory to get bigger a bit over time but it's increasing with multiple GBs per day.

Steps to reproduce the behavior
-------------------------------
Make sure there is a local cache available, run a backup and check the timing on this one. Afterwards run `restic cache --cleanup --max-age=0` on a repository which has a local cache. Run another backup a it should be just a quick as before removing the cache.

Do you have any idea what may have caused this?
-----------------------------------------------
I have two suspicions: 
- Restic may be reading the metadata from the repositories? I would still think that must be much slower than reading local directories/files.
- The `--cleanup-cache` flags doesn't 'see' or use the local cache directory properly because of the docker volume in some way? It does when writing but maybe it doesn't when reading it. 

Do you have an idea how to solve the issue?
-------------------------------------------
I've tried numerous things to find out what causes the issue (if it's an issue after all, maybe I'm misunderstanding the way caching works and why the directories get big pretty fast).

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Not only today ;) Amazing tool you guys made!
