### ISSUE TITLE
Restic Mount cannot find OSXFUSE

### ISSUE THREAD

**Issue by bjesuiter** [restic/restic#4091]
Output of `restic version`
--------------------------
restic 0.14.0 compiled with go1.19 on darwin/amd64

How did you run restic exactly?
-------------------------------
via [arctic-hen7](https://github.com/arctic-hen7)/[bonnie](https://github.com/arctic-hen7/bonnie) and [doppler](https://doppler.com/). 

I think, that the error here is within restic, somewhere in the library which searches for OSX, 
see this issue: https://github.com/restic/restic/issues/4048

But here are my commands anyway: 

```toml
# bonnie.toml file locatet in ~/
# This file contains the main scripts which should be run from $HOME
# All other infos, like restic repostiory come from ENV Variables stored in doppler!
# Docs of bonnie: https://github.com/arctic-hen7/bonnie/wiki

version = "0.3.2"

[scripts.restic]
    cmd = 'doppler run -- restic %%'

[scripts.restic-snapshots]
    cmd = 'bonnie restic snapshots'

[scripts.restic-mount]
    cmd = [
        'mkdir -p /tmp/restic',
        'bonnie restic mount /tmp/restic'
    ]

```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
```sh
# Env-Vars used
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
RESTIC_PASSWORD #(custom env var, read by doppler cli)
RESTIC_PASSWORD_COMMAND = doppler secrets get --plain -p bjesuiter-home -c dev RESTIC_PASSWORD
RESTIC_REPOSITORY: s3:https://s3.eu-west-1.wasabisys.com/<my-bucket>
```

```sh
# The restic command run: 
mkdir -p /tmp/restic
bonnie restic mount /tmp/restic

# Output: 
repository 98538ede opened (repository version 2) successfully, password is correct
cannot locate OSXFUSE
unable to umount (maybe already umounted or still in use?): unmount /tmp/restic: operation not permitted
```

Expected behavior
-----------------

Since I've installed macFUSE from here in version 4.4.1, I assumed it would be able to load it for mounting a snapshot: https://osxfuse.github.io/

Actual behavior
---------------

I seems to search for OSXFUSE, which is the old name of macFUSE during the OS X Days.

Steps to reproduce the behavior
-------------------------------

simply try to mount a snapshot on macos

Do you have any idea what may have caused this?
-----------------------------------------------

- The Library in use should be https://github.com/anacrolix/fuse now, based on this issue: https://github.com/restic/restic/issues/4048
- On the github readme it says, they implemented compatiblity with macFUSE after the change from osxfuse. 
- To rule out environment differences due to bonnie, I ran the command without it (doppler and restic alone) . 
This is also not working: 

```
doppler run -- restic mount /tmp/restic
repository 98538ede opened (repository version 2) successfully, password is correct
cannot locate OSXFUSE
unable to umount (maybe already umounted or still in use?): unmount /tmp/restic: operation not permitted
```

Do you have an idea how to solve the issue?
-------------------------------------------

probably something with the library, but you seem to be on top of that anyway in https://github.com/restic/restic/issues/4048

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

YES! It helped me to backup my Obsidian Notes folder and a cryptomator container which is awesome! 
I only wanted to check, If the cryptomator container can be successfully opend from the restic backup via restic mount ^^

This is the first real restic backup setup I build, so if this goes well, I'll add many more restic backups!
