### ISSUE TITLE
[0.17.0+] backup command reports "Access is denied" errors on Windows

### ISSUE THREAD

**Issue by amorphobia** [restic/restic#5103]
Output of `restic version`
--------------------------
0.17.0+

What backend/service did you use to store the repository?
---------------------------------------------------------
Another local drive on Windows

Problem description / Steps to reproduce
----------------------------------------
```Powershell
restic backup "F:\library" --exclude "F:\library\thumbs" --exclude "F:\library\encoded-video"
```

Expected behavior
-----------------
No error.

Actual behavior
---------------
Show following errors on every dirs and files:
```
error: incomplete metadata for F:\library\database-backup: get named security info failed with: Access is denied.
```

Do you have any idea what may have caused this?
-----------------------------------------------
Tested with 0.16.5 and got no errors.

**Comment by rawtaz** [comment]
Can you please try to reproduce the problem with the latest restic 0.17.2 which you can download at https://github.com/restic/restic/releases ?

**Comment by amorphobia** [comment]
Updated to 0.17.2, still got same error.

The folder to backup was the library of [immich app](https://github.com/immich-app/immich), which I was running with docker on Windows. The dirs are mapped to the ones inside the docker container. I'm not sure if the access error is related to this.

**Comment by andydld** [comment]
Same here since 0.17.2, but with VSS and backing up Hyper-V-based virtual machines on an Windows Server 2022 Standard.

CLI:

restic --limit-upload 1220 --verbose --use-fs-snapshot --compression=max backup C:\Hyper-V\SRV02

Log (the Windows-error is in german):

open repository
using parent snapshot 2c9cacd3
load index files
start scan on [C:\Hyper-V\SRV02]
start backup on [C:\Hyper-V\SRV02]
creating VSS snapshot for [c:\]
successfully created snapshot for [c:\]
error: incomplete metadata for C:\: multiple errors occurred: [get named security info failed with: Zugriff verweigert; get EA failed while opening file handle for path \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy52\, with: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
scan finished in 6.700s: 13 files, 145.731 GiB

Files:           0 new,     4 changed,     9 unmodified
Dirs:            0 new,     6 changed,     9 unmodified
Data Blobs:  19809 new
Tree Blobs:      6 new
Added to the repository: 14.071 GiB (6.083 GiB stored)

processed 13 files, 145.731 GiB in 1:27:37
snapshot 1ee4fc7e saved
Warning: at least one source file could not be read

I had no problems with 0.17.1.

**Comment by MichaelEischer** [comment]
> error: incomplete metadata for C:: multiple errors occurred: [get named security info failed with: Zugriff verweigert; get EA failed while opening file handle for path \?\GLOBALROOT\Device\HarddiskVolumeShadowCopy52, with: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

@andydld Sigh, yet another permission error. Your error is related to VSS, which is a separate issue. Please open a new issue. Apparently we'll need an exception there.

**Comment by amorphobia** [comment]
> How exactly are the docker containers dirs mounted on Windows?

The working directory is `F:\`.

<details>
<summary>docker-compose.yml</summary>

```yaml
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: vaapi-wsl # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: openvino-wsl # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

</details>

<details>
<summary>.env</summary>

```
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Asia/Shanghai

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

</details>

The volume mappings were not changed at all from day one and work fine with restic 0.16.5
